# Generated by Django 3.2.12 on 2023-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('joining_year', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
