# Generated by Django 3.2.12 on 2023-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20230516_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='joining_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='reg_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
