# Generated by Django 3.2.12 on 2023-05-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20230516_1738'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grades', models.CharField(max_length=100)),
                ('reviewer', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
        ),
    ]
