# Generated by Django 3.2.12 on 2023-05-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20230516_1738'),
        ('grades', '0002_usergrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrades',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grades.departments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergrades',
            name='semester',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='grades.semesters'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usergrades',
            unique_together={('user', 'department', 'semester', 'subject')},
        ),
    ]
