# Generated by Django 3.2.12 on 2023-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20230520_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrades',
            name='reviewer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
