# Generated by Django 3.2.12 on 2023-05-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20230520_0725'),
        ('grades', '0005_auto_20230520_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrades',
            name='reviewer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usergrades',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup'),
        ),
    ]
