# Generated by Django 3.0.7 on 2023-05-20 19:40

from django.db import migrations, models
import grades.models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_savepdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsx_files', models.FileField(storage=grades.models.OverwriteStorage(), upload_to='')),
            ],
        ),
    ]
