# Generated by Django 3.0.7 on 2023-05-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_resultfiles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergrades',
            unique_together=set(),
        ),
    ]
