# Generated by Django 3.0.7 on 2023-05-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20230520_1045'),
        ('grades', '0010_auto_20230520_1949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergrades',
            unique_together={('user', 'department', 'semester', 'subject')},
        ),
    ]
